version: '3.0'

expectations:
  population_size: 1000

actions:
  # Generates study population for CV, mental health outcomes
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2020-03-01 to 2020-06-01 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv
  # Generates study population for diabetes outcomes
  generate_study_population_dm:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_dm --index-date-range "2020-03-01 to 2020-06-01 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_dm_*.csv
  # Generates summary measures for CV and mental health outcomes
  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_*.csv
  # Generates summary measures for diabetes outcomes  
  calculate_measures_dm:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_dm --output-dir=output/measures
    needs: [generate_study_population_dm]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_dm_*.csv

  # Generates graphs for diabetes cohort
  Graphs:
    run: stata-mp:latest analysis/graphs_dm.do 
    needs: [calculate_measures_dm]
    outputs: 
      moderately_sensitive:
        log: logs/check.log
        output: output/line_*.eps

    

