version: '3.0'

expectations:
  population_size: 1000

actions:
  # Generates study population for CV, mental health outcomes
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv
  # Generates study population for diabetes outcomes
  generate_study_population_dm:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_dm --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures/dm --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/dm/input_dm_*.csv

  # Generates study population for respiratory outcomes
  generate_study_population_resp:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_resp --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures/resp --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/resp/input_resp_*.csv

  # Generates study population for mortality
  generate_study_population_mortality:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_mortality --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures/mortality --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/mortality/input_mortality_*.csv
  
  # Generates study populations for baseline tables at 3 timepoints
  generate_study_population_tables_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2019-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2019-01-01.csv
  generate_study_population_tables_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2020-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2020-01-01.csv
  generate_study_population_tables_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2021-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2021-01-01.csv
  
  # Generates summary measures for CV and mental health outcomes
  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure: output/measures/measure_*.csv
  # Generates summary measures for diabetes outcomes  
  calculate_measures_dm:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_dm --output-dir=output/measures/dm
    needs: [generate_study_population_dm]
    outputs:
      moderately_sensitive:
        measure: output/measures/dm/measure_dm_*.csv

  # Generates summary measures for respiratory outcomes  
  calculate_measures_resp:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_resp --output-dir=output/measures/resp
    needs: [generate_study_population_resp]
    outputs:
      moderately_sensitive:
        measure: output/measures/resp/measure_*.csv

  # Generates summary measures for mortality outcomes  
  calculate_measures_mortality:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_mortality --output-dir=output/measures/mortality
    needs: [generate_study_population_mortality]
    outputs:
      moderately_sensitive:
        measure: output/measures/mortality/measure_*.csv
  
  # Generates graphs for CVD & mental health outcomes
  graphs_mh_cvd:
    run: stata-mp:latest analysis/graphs_mh_cvd.do 
    needs: [calculate_measures]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_mh_cvd.log
        output: output/line_*.eps
      highly_sensitive:
        output: output/measures/collapse_measure_*
  # Generates graphs for diabetes outcomes
  graphs_dm:
    run: stata-mp:latest analysis/graphs_dm.do 
    needs: [calculate_measures_dm]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_dm.log
        output: output/line_dm_*.eps
      highly_sensitive:
        output: output/measures/dm/collapse_measure_*
  # Generate graphs for respiratory outcomes
  graphs_resp:
    run: stata-mp:latest analysis/graphs_resp.do 
    needs: [calculate_measures_resp]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_resp.log
        output: output/line_resp_*.eps
      highly_sensitive:
        output: output/measures/resp/collapse_measure_*

  # Generate graphs for mortality
  graphs_mortality:
    run: stata-mp:latest analysis/graphs_mortality.do 
    needs: [calculate_measures_mortality]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_mortality.log
        output: output/graphs/line_mortality_*.svg
      highly_sensitive:
        output: output/collapsed/collapse_measure_*
        
  # Running analysis scripts
  model_checks_dm:
    run: stata-mp:latest analysis/model_check_dm.do
    needs: [calculate_measures_dm]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_dm.log
        output: output/time_series/dm_*.eps

  model_checks_resp:
    run: stata-mp:latest analysis/model_check_resp.do
    needs: [calculate_measures_resp, graphs_resp]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_resp.log
        output: output/time_series/resp_*.eps

  model_checks_cvd:
    run: stata-mp:latest analysis/model_check_cvd.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_cvd.log
        output: output/time_series/cvd_*.eps

  model_checks_mh:
    run: stata-mp:latest analysis/model_check_mh.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_mh.log
        output: output/time_series/mh_*.eps

  model_checks_mortality:
    run: stata-mp:latest analysis/model_check_mortality.do
    needs: [calculate_measures_mortality, graphs_mortality]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_mortality.log
        output: output/time_series/mortality_*.eps
  
  time_series_resp:
    run: stata-mp:latest analysis/time_series_resp.do
    needs: [calculate_measures_resp]
    outputs:
      moderately_sensitive:
        log: logs/tsreg.log
        output: output/time_series/tsreg_tables.xlsx

