version: '3.0'

expectations:
  population_size: 1000

actions:
  # Generating static variables 
  generate_study_population_static:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static.csv

  # Generating static variables 
  generate_study_population_static_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_static_2020 --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_static_2020.csv
  # Generates study population for CV - start date = 2018-03-01
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_*.csv
  # Join static and time-varying variables
  join_cohorts_cvd:
    run: >
      cohort-joiner:v0.0.30
        --lhs output/measures/input_*.csv
        --rhs output/input_static.csv
        --output-dir output/measures/cvd
    needs: [generate_study_population, generate_study_population_static]
    outputs: 
      highly_sensitive:
        cohort: output/measures/cvd/input_*.csv
  join_cohorts_cvd_2020:
    run: >
      cohort-joiner:v0.0.30
        --lhs output/measures/input_*.csv
        --rhs output/input_static_2020.csv
        --output-dir output/measures/cvd/test
    needs: [generate_study_population, generate_study_population_static_2020]
    outputs: 
      highly_sensitive:
        cohort: output/measures/cvd/test/input_*.csv
  # Generates study population for mental health outcomes - start date = 2018-03-01
  generate_study_population_mh:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_mh --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/measures/input_mh_*.csv
  # Join static and time-varying variables
  join_cohorts_mh:
    run: >
      cohort-joiner:v0.0.30
        --lhs output/measures/input_mh_*.csv
        --rhs output/input_static.csv
        --output-dir output/measures/mh
    needs: [generate_study_population_mh, generate_study_population_static]
    outputs: 
      highly_sensitive:
        cohort: output/measures/mh/input_mh_*.csv

  # Check join
  join_check:
    run: stata-mp:latest analysis/variable_check.do 
    needs: [join_cohorts_cvd, join_cohorts_mh, join_cohorts_cvd_2020]
    outputs: 
      moderately_sensitive:
        log: logs/missing_check.log
  # Generates study population for diabetes outcomes
  generate_study_population_dm:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_dm --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures/dm --output-format=csv 
    outputs:
      highly_sensitive:
        cohort: output/measures/dm/input_dm_*.csv

  # Generates study population for respiratory outcomes
  generate_study_population_resp:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_resp --index-date-range "2018-03-01 to 2022-01-31 by month" --output-dir=output/measures/resp --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/resp/input_resp_*.csv

  # Generates study population for mortality
  generate_study_population_mortality:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_mortality --index-date-range "2019-02-01 to 2022-01-31 by month" --output-dir=output/measures/mortality --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/mortality/input_mortality_*.csv
  
  # Generates study populations for baseline tables at 3 timepoints
  generate_study_population_tables_2019:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2019-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2019-01-01.csv
  generate_study_population_tables_2020:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2020-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2020-01-01.csv
  generate_study_population_tables_2021:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_tables --index-date-range "2021-01-01" --output-dir=output/measures/tables --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/measures/tables/input_tables_2021-01-01.csv
  
  # Generates baseline tables
  create_baseline_tables:
    run: stata-mp:latest analysis/baseline_tables.do
    needs: [generate_study_population_tables_2019, generate_study_population_tables_2020, generate_study_population_tables_2021]
    outputs:
      moderately_sensitive:
        log: logs/table1_descriptives.log
        output: output/tables/baseline_table_*.csv

  # Generates summary measures for CV 
  calculate_measures:
    run: cohortextractor:latest  generate_measures --study-definition study_definition --output-dir=output/measures/cvd
    needs: [join_cohorts_cvd]
    outputs:
      moderately_sensitive:
        measure: output/measures/cvd/measure_*_rate.csv
  # Generates summary measures for mental health outcomes
  calculate_measures_mh:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_mh --output-dir=output/measures/mh
    needs: [join_cohorts_mh]
    outputs:
      moderately_sensitive:
        measure: output/measures/mh/measure_*_rate.csv
  # Generates summary measures for diabetes outcomes  
  calculate_measures_dm:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_dm --output-dir=output/measures/dm
    needs: [generate_study_population_dm]
    outputs:
      moderately_sensitive:
        measure: output/measures/dm/measure_dm_*_rate.csv

  # Generates summary measures for respiratory outcomes  
  calculate_measures_resp:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_resp --output-dir=output/measures/resp
    needs: [generate_study_population_resp]
    outputs:
      moderately_sensitive:
        measure: output/measures/resp/measure_*_rate.csv

  # Generates summary measures for mortality outcomes  
  calculate_measures_mortality:
    run: cohortextractor:latest  generate_measures --study-definition study_definition_mortality --output-dir=output/measures/mortality
    needs: [generate_study_population_mortality]
    outputs:
      moderately_sensitive:
        measure: output/measures/mortality/measure_*_rate.csv
  
  # Generates graphs for CVD & mental health outcomes
  graphs_mh_cvd:
    run: stata-mp:latest analysis/graphs_mh_cvd.do 
    needs: [calculate_measures, calculate_measures_mh]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_mh_cvd.log
        output: output/graphs/line_*.svg
     
  # Generates graphs for diabetes outcomes
  graphs_dm:
    run: stata-mp:latest analysis/graphs_dm.do 
    needs: [calculate_measures_dm]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_dm.log
        output: output/graphs/line_dm_*.svg
      highly_sensitive:
        output: output/collapsed/collapse_measure_dm_*
  # Generate graphs for respiratory outcomes
  graphs_resp:
    run: stata-mp:latest analysis/graphs_resp.do 
    needs: [calculate_measures_resp]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_resp.log
        output: output/graphs/line_resp_*.svg

  # Generate graphs for mortality
  graphs_mortality:
    run: stata-mp:latest analysis/graphs_mortality.do 
    needs: [calculate_measures_mortality]
    outputs: 
      moderately_sensitive:
        log: logs/graphs_mortality.log
        output: output/graphs/line_mortality_*.svg
        
  # Running analysis scripts
  model_checks_dm:
    run: stata-mp:latest analysis/model_check_dm.do
    needs: [calculate_measures_dm]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_dm.log
        output: output/time_series/dm_*.svg

  model_checks_resp:
    run: stata-mp:latest analysis/model_check_resp.do
    needs: [calculate_measures_resp]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_resp.log
        output: output/time_series/resp_*.svg

  model_checks_cvd:
    run: stata-mp:latest analysis/model_check_cvd.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_cvd.log
        output: output/time_series/cvd_*.svg

  model_checks_mh:
    run: stata-mp:latest analysis/model_check_mh.do
    needs: [calculate_measures_mh]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_mh.log
        output: output/time_series/mh_*.svg

  model_checks_mortality:
    run: stata-mp:latest analysis/model_check_mortality.do
    needs: [calculate_measures_mortality]
    outputs:
      moderately_sensitive: 
        log: logs/model_checks_mortality.log
        output: output/time_series/mortality_*.svg
  
  time_series_resp:
    run: stata-mp:latest analysis/time_series_resp.do
    needs: [calculate_measures_resp]
    outputs:
      moderately_sensitive:
        log: logs/tsreg_resp.log
        output: output/time_series/tsreg_resp*.csv
        graph: output/time_series/margins_resp*.svg

  time_series_dm:
    run: stata-mp:latest analysis/time_series_dm.do
    needs: [calculate_measures_dm]
    outputs:
      moderately_sensitive:
        log: logs/tsreg_dm.log
        output: output/time_series/tsreg_dm*.csv
        graph: output/time_series/margins_dm*.svg

  time_series_cvd:
    run: stata-mp:latest analysis/time_series_cvd.do
    needs: [calculate_measures]
    outputs:
      moderately_sensitive:
        log: logs/tsreg_cvd.log
        output: output/time_series/tsreg_cvd_*.csv
        graphs: output/time_series/margins_cvd*.svg

  time_series_mh:
    run: stata-mp:latest analysis/time_series_mh.do
    needs: [calculate_measures_mh]
    outputs:
      moderately_sensitive:
        log: logs/tsreg_mh.log
        output: output/time_series/tsreg_mh*.csv
        graphs: output/time_series/margins_mh*.svg

  time_series_mortality:
    run: stata-mp:latest analysis/time_series_mortality.do
    needs: [calculate_measures_mortality]
    outputs:
      moderately_sensitive:
        log: logs/tsreg_mortality.log
        output: output/time_series/tsreg_mortality*.csv
        graph: output/time_series/margins_mort*.svg

  # Study definition for pre-pandemic survival analysis
  generate_study_population_survival_pre:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_survival_pre --output-dir=output/survival --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/survival/input_survival_pre*.csv

  # Study definition for pandemic survival analysis
  generate_study_population_survival_pandemic:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_survival_pandemic --output-dir=output/survival --output-format=csv --skip-existing
    outputs:
      highly_sensitive:
        cohort: output/survival/input_survival_pandemic*.csv

  # Cox models
  cox_models:
    run: stata-mp:latest analysis/cox_models.do
    needs: [generate_study_population_survival_pre, generate_study_population_survival_pandemic]
    outputs:
      moderately_sensitive:
        log: logs/cox_model_checks.log
        output: output/tables/*.txt
        graph: output/graphs/km*.svg
        